#Ultimo acceso
#Thu Jul 13 17:09:41 ART 2023
server=https\://octopusmanager.space
powerpointRoute=C\:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE
mediaRoute=C\:\\Program Files (x86)\\K-Lite Codec Pack\\MPC-HC64\\mpc-hc64.exe
data=C\:\\Users\\Evento\\Documents\\octopus2
idioma=Ingles
adminPass=octo
eventPrefix=sadi-ic
pdfRoute=C\:\\Program Files\\Adobe\\Acrobat DC\\Acrobat\\Acrobat.exe
server_storage=https\://storageoctopus.online
sala=B
salaId=45
logo=C\:\\Users\\Evento\\Downloads\\WhatsApp Image 2022-06-27 at 7.39.34 PM.jpeg
eventName=International congress of variatic surgery
res_x=1280
res_y=768
