#Ultimo acceso
#Mon Oct 02 15:52:00 ART 2023
powerpointRoute=
server=https\://octopusmanager.space
mediaRoute=
data=C\:\\Users\\Evento\\Documents
idioma=Espanol
adminPass=octo
res_y=720
eventPrefix=slipe
script=
pdfRoute=
res_x=1366
server_storage=https\://storageoctopus.online
sala=Sala 1
salaId=46
logo=C\:\\Users\\Evento\\Documents\\Octopus\\data\\cursoslipe-logo-b.png
eventName=CURSO PEDI\u00C1TRICA Y VACUNAS
