#Ultimo acceso
#Mon Aug 28 12:33:43 ART 2023
powerpointRoute=
server=https\://octopusmanager.space
mediaRoute=
data=
idioma=Espanol
adminPass=octo
res_y=720
eventPrefix=slipe
script=
pdfRoute=
res_x=1280
server_storage=https\://storageoctopus.online
sala=
salaId=46
logo=C\:\\Users\\Evento\\Documents\\Octopus\\data\\.png
eventName=CURSO INTERNACIONAL ACTUALIDAD EN INFECTOLOG\u00CDA PEDI\u00C1TRICA Y VACUNAS
