#Setting.java
conf-titulo=Configuracion
conf-nombre-evento=Nombre del evento
conf-sala=Sala
conf-sala-pos-0=Elija una sala...
conf-logo=Logo
conf-servidor=Servidor
conf-codigo-evento=Codigo de Evento
conf-powerpoint=Ruta Powerpoint
conf-video=Ruta VideoPlayer
conf-pdf=Ruta PDF
conf-btn-seleccionar=Seleccionar
conf-btn-guardar=Guardar
conf-btn-cancelar=Cancelar
conf-data=Ruta de datos
conf-btn-data=Seleccionar
#Password.java
pass-titulo=Administrador
pass-ingrese=Ingrese la contraseña
pass-error=La contraseña es incorrecta!
#EventView.java
event-sala=SALA
event-bienvenida=BIENVENIDOS
event-inicio-tabla=Inicio
event-cierre-tabla=Cierre
event-bloque-tabla=Sesión
event-inicio-tabla=Entrar
#Error.java
err-conexion=Error de conexión