#Setting.java
conf-titulo=Settings
conf-nombre-evento=Event Name 
conf-sala=Room
conf-sala-pos-0=Select a room...
conf-logo=Logo
conf-servidor=Server
conf-codigo-evento=Event code
conf-powerpoint=Path Powerpoint/Keynote
conf-video=Path VideoPlayer
conf-pdf=Path PDF
conf-btn-seleccionar=Select
conf-btn-guardar=Save
conf-btn-cancelar=Cancel
conf-data=Presentation path
conf-btn-data=Select
conf-script=Path Script
conf-btn-script=Select
conf-btn-conectar=Connect
conf_res_x=Width(px)
conf_res_y=Heigth(px)
#Password.java
pass-titulo=Administrator
pass-ingrese=Password
pass-error=Password incorrect!
#EventView.java
event-sala=ROOM
event-bienvenida=WELCOME
event-inicio-tabla=Start
event-cierre-tabla=End
event-bloque-tabla=Session
event-inicio-tabla=Enter
#Error.java
err-conexion=Connection error