#Ultimo acceso
#Fri Aug 25 17:08:30 ART 2023
1280=
720=
adminPass=octo
data=
eventName=asdasda
eventPrefix=
idioma=Espanol
logo=
mediaRoute=
pdfRoute=
powerpointRoute=
sala=
salaId=
server=
server_storage=https\://storageoctopus.online
